name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: docker pull ankitkj199/node-express-hello-world:latest

      - name: Run New Docker Container
        run: |
          docker stop cicd-pipeline-container || true
          docker rm cicd-pipeline-container || true
          docker run -d -p 8080:8080 --name cicd-pipeline-container-new ankitkj199/node-express-hello-world:latest

      - name: Cleanup Old Container
        run: |
          docker stop cicd-pipeline-container-old || true
          docker rename cicd-pipeline-container cicd-pipeline-container-old || true
          docker rename cicd-pipeline-container-new cicd-pipeline-container || true
          docker rm cicd-pipeline-container-old || true
