# name: Docker Image CI

# on:
#   push:
#     branches: [ "master" ]
  

# jobs:

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4
#     - name: Login Dockerhub
#       env:
#         DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
#         DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
#       run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

#     - name: Build the Docker image
#       run: docker build -t node-express-hello-world .
#     - name: Push to Dockerhub
#       run: docker push ankitkj199/node-express-hello-world:latest
      


name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

    - name: Build and tag the Docker image
      run: docker build -t ankitkj199/node-express-hello-world:latest .

    - name: Push the Docker image
      run: docker push ankitkj199/node-express-hello-world:latest
